"""Evidence-first claim auditing over completed ``document_extract`` output."""

from .client import ClaimEvidence
from .config import Settings
from .errors import (
    ClaimEvidenceError,
    DependencyUnavailableError,
    IndexNotReadyError,
    NotFoundError,
    ValidationError,
)
from .progress import ProgressCallback
from .models import (
    AuditTrace,
    Citation,
    ClaimResult,
    DecisionExplanation,
    DocumentSummary,
    EvidenceComparison,
    EvidenceDetail,
    EvidenceKind,
    EvidenceMatch,
    EvidenceQuality,
    GeometryPrecision,
    HealthReport,
    IndexReference,
    IngestReport,
    ModelHealth,
    NumericComparison,
    ProgressEvent,
    QualifierComparison,
    Region,
    RegionRole,
    RemovalReport,
    TraceCandidate,
    Verdict,
    VersionStatus,
)

__version__ = "0.2.0"

__all__ = [
    "AuditTrace",
    "Citation",
    "ClaimEvidence",
    "ClaimEvidenceError",
    "ClaimResult",
    "DecisionExplanation",
    "DependencyUnavailableError",
    "DocumentSummary",
    "EvidenceComparison",
    "EvidenceDetail",
    "EvidenceKind",
    "EvidenceMatch",
    "EvidenceQuality",
    "GeometryPrecision",
    "HealthReport",
    "IndexNotReadyError",
    "IndexReference",
    "IngestReport",
    "ModelHealth",
    "NotFoundError",
    "NumericComparison",
    "ProgressCallback",
    "ProgressEvent",
    "QualifierComparison",
    "Region",
    "RegionRole",
    "RemovalReport",
    "Settings",
    "TraceCandidate",
    "ValidationError",
    "Verdict",
    "VersionStatus",
    "__version__",
]
